version: '2.4'
services:
  db:
    image: mysql
    container_name: serviceorder_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - serviceorder_data:/var/lib/mysql

volumes:
  serviceorder_data:
