spring:
  application:
    name: serviceOrderAPI
  datasource:
    url: jdbc:mysql://localhost:3306/serviceOrder?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
